### ISSUE TITLE
Allow `AProgressbar` to accept custom classes/styles to the progress element.

### ISSUE THREAD

**Issue by Graham187K** [cisco-sbg-ui/magna-react#431]
**Is your feature request related to a problem? Please describe.**
Investigate has a requirement to change the `AProgressbar` color to indicate the investigation is complete.
Due to scoping when using CSS modules, this becomes difficult.

**Describe the solution you'd like**
Could we have the ability to pass `style` or `className` props directly to the progress bar element. Currently, any `className` provided is only passed to the parent wrapper div of the component.

**Additional context**

```js
// .jsx
<AProgressbar className={css.progressBar}
```

This currently does not work to set the progress bar to $green55
```scss
// .module.scss
.progress-bar {
  .a-progressbar__fill {
    background-color: $green55;
  }
}
```

This works but is a little hacky. I would be nice if I could pass a modifier class directly to `.a-progressbar__fill`
```scss
// .module.scss
.progress-bar {
  :global(.a-progressbar__fill) {
    background-color: $green55;
  }
}
```
